## 📊 Summary Table

| Tensor Dimension | Common Name | Machine Learning Use Case     | Example Shape              | Example Application          |
|------------------|------------|--------------------------------|----------------------------|------------------------------|
| 1D               | Vector     | Single feature list            | (3,)                       | Features of one house        |
| 2D               | Matrix     | Tabular dataset                | (100, 3)                   | House price dataset          |
| 3D               | 3D Tensor  | Sequence or single image       | (32, 50, 128)              | NLP embeddings               |
| 4D               | 4D Tensor  | Batch of images                | (32, 128, 128, 3)          | CNN image classification     |
| 5D               | 5D Tensor  | Batch of videos                | (16, 30, 128, 128, 3)      | Video classification         |

### Zero Dimensional Tensors

In [2]:
import numpy as np 

In [3]:
zero_D = np.array(4)
print(zero_D)
print(f"Dimension of {zero_D} is ", zero_D.ndim)

4
Dimension of 4 is  0


### One Dimensional Tensors

In [6]:
one_d = np.array([1,2,3])
print(one_d)
print(f"Dimension of {one_d} is ", one_d.ndim)

[1 2 3]
Dimension of [1 2 3] is  1


### Two Dimensional Tensors

In [7]:
two_D = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,5]])
print(two_D)
print(f"Dimension of {two_D} is ", two_D.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 5]]
Dimension of [[1 2 3]
 [4 5 6]
 [7 8 5]] is  2


### Three Dimensional Tensors

In [10]:
#3D TENSOR 
three_D = np.array([[1,0,0,0],[0,1,0,0],
                   [1,0,0,0],[0,0,1,0],
                   [1,0,0,0],[0,0,0,1]])
print(three_D)

[[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]]


In [11]:
print(f"Dimension of {three_D} is ", three_D.ndim)

Dimension of [[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]] is  2


In [13]:
shape_of_three_D = three_D.shape
print(f"Shape of {three_D} is ", shape_of_three_D)

Shape of [[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 0 0 1]] is  (6, 4)


In [15]:
#4D TENSOR
four_D = np.array([[[[1,0,0,0],[0,1,0,0],
                   [1,0,0,0],[0,0,1,0],
                   [1,0,0,0],[0,0,0,1]]],
                   [[[1,0,0,0],[0,1,0,0],
                   [1,0,0,0],[0,0,1,0],
                   [1,0,0,0],[0,0,0,1]]]])
print(four_D)
print(four_D.ndim)
shape_of_four_D = four_D.shape
print(shape_of_four_D)


[[[[1 0 0 0]
   [0 1 0 0]
   [1 0 0 0]
   [0 0 1 0]
   [1 0 0 0]
   [0 0 0 1]]]


 [[[1 0 0 0]
   [0 1 0 0]
   [1 0 0 0]
   [0 0 1 0]
   [1 0 0 0]
   [0 0 0 1]]]]
4
(2, 1, 6, 4)
